/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dj.model.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CompositionAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3986783932240463429L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompositionAvro\",\"namespace\":\"com.dj.model.avro\",\"fields\":[{\"name\":\"comp1\",\"type\":\"string\"},{\"name\":\"comp2\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CompositionAvro> ENCODER =
      new BinaryMessageEncoder<CompositionAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CompositionAvro> DECODER =
      new BinaryMessageDecoder<CompositionAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CompositionAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CompositionAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CompositionAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CompositionAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CompositionAvro from a ByteBuffer. */
  public static CompositionAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence comp1;
   private java.lang.CharSequence comp2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CompositionAvro() {}

  /**
   * All-args constructor.
   * @param comp1 The new value for comp1
   * @param comp2 The new value for comp2
   */
  public CompositionAvro(java.lang.CharSequence comp1, java.lang.CharSequence comp2) {
    this.comp1 = comp1;
    this.comp2 = comp2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return comp1;
    case 1: return comp2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: comp1 = (java.lang.CharSequence)value$; break;
    case 1: comp2 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'comp1' field.
   * @return The value of the 'comp1' field.
   */
  public java.lang.CharSequence getComp1() {
    return comp1;
  }

  /**
   * Sets the value of the 'comp1' field.
   * @param value the value to set.
   */
  public void setComp1(java.lang.CharSequence value) {
    this.comp1 = value;
  }

  /**
   * Gets the value of the 'comp2' field.
   * @return The value of the 'comp2' field.
   */
  public java.lang.CharSequence getComp2() {
    return comp2;
  }

  /**
   * Sets the value of the 'comp2' field.
   * @param value the value to set.
   */
  public void setComp2(java.lang.CharSequence value) {
    this.comp2 = value;
  }

  /**
   * Creates a new CompositionAvro RecordBuilder.
   * @return A new CompositionAvro RecordBuilder
   */
  public static com.dj.model.avro.CompositionAvro.Builder newBuilder() {
    return new com.dj.model.avro.CompositionAvro.Builder();
  }

  /**
   * Creates a new CompositionAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CompositionAvro RecordBuilder
   */
  public static com.dj.model.avro.CompositionAvro.Builder newBuilder(com.dj.model.avro.CompositionAvro.Builder other) {
    return new com.dj.model.avro.CompositionAvro.Builder(other);
  }

  /**
   * Creates a new CompositionAvro RecordBuilder by copying an existing CompositionAvro instance.
   * @param other The existing instance to copy.
   * @return A new CompositionAvro RecordBuilder
   */
  public static com.dj.model.avro.CompositionAvro.Builder newBuilder(com.dj.model.avro.CompositionAvro other) {
    return new com.dj.model.avro.CompositionAvro.Builder(other);
  }

  /**
   * RecordBuilder for CompositionAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompositionAvro>
    implements org.apache.avro.data.RecordBuilder<CompositionAvro> {

    private java.lang.CharSequence comp1;
    private java.lang.CharSequence comp2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dj.model.avro.CompositionAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.comp1)) {
        this.comp1 = data().deepCopy(fields()[0].schema(), other.comp1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.comp2)) {
        this.comp2 = data().deepCopy(fields()[1].schema(), other.comp2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CompositionAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dj.model.avro.CompositionAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.comp1)) {
        this.comp1 = data().deepCopy(fields()[0].schema(), other.comp1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.comp2)) {
        this.comp2 = data().deepCopy(fields()[1].schema(), other.comp2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'comp1' field.
      * @return The value.
      */
    public java.lang.CharSequence getComp1() {
      return comp1;
    }

    /**
      * Sets the value of the 'comp1' field.
      * @param value The value of 'comp1'.
      * @return This builder.
      */
    public com.dj.model.avro.CompositionAvro.Builder setComp1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.comp1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'comp1' field has been set.
      * @return True if the 'comp1' field has been set, false otherwise.
      */
    public boolean hasComp1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'comp1' field.
      * @return This builder.
      */
    public com.dj.model.avro.CompositionAvro.Builder clearComp1() {
      comp1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'comp2' field.
      * @return The value.
      */
    public java.lang.CharSequence getComp2() {
      return comp2;
    }

    /**
      * Sets the value of the 'comp2' field.
      * @param value The value of 'comp2'.
      * @return This builder.
      */
    public com.dj.model.avro.CompositionAvro.Builder setComp2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.comp2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'comp2' field has been set.
      * @return True if the 'comp2' field has been set, false otherwise.
      */
    public boolean hasComp2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'comp2' field.
      * @return This builder.
      */
    public com.dj.model.avro.CompositionAvro.Builder clearComp2() {
      comp2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CompositionAvro build() {
      try {
        CompositionAvro record = new CompositionAvro();
        record.comp1 = fieldSetFlags()[0] ? this.comp1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.comp2 = fieldSetFlags()[1] ? this.comp2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CompositionAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<CompositionAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CompositionAvro>
    READER$ = (org.apache.avro.io.DatumReader<CompositionAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
